package_assets: on
compress_assets: on
template_function: _.template

javascripts:
  common:
    - public/javascripts/common/**/*.js
  shelby:
    # JSTs
    - app/views/templates/**/*.jst
    # backbone && underscore
    - public/javascripts/backbone/underscore.js
    - public/javascripts/backbone/backbone.js
    - public/javascripts/backbone/backbone-relational.js
    - public/javascripts/backbone/backbone-support/support.js
    - public/javascripts/backbone/backbone-support/swapping_router.js
    - public/javascripts/backbone/backbone-support/composite_view.js
    #underscore mixins
    - public/javascripts/underscore.inflection.js
    # hacked order
    - public/javascripts/app/views/list_item.view.js
    - public/javascripts/app/views/frame.view.js
    - public/javascripts/app/views/list.view.js
    - public/javascripts/app/views/dashboard.view.js
    # shelby backbone app
    - public/javascripts/app/app.js
    - public/javascripts/app/routers/*.js
    - public/javascripts/app/models/*.js
    - public/javascripts/app/collections/*.js
    - public/javascripts/app/views/**/*.js
    - public/javascripts/app/utils/*.js

stylesheets:
  common:
    - public/stylesheets/screen.css
  #h5bp:
    #- public/stylesheets/h5bp/*.css
