package_assets: on
compress_assets: on #using YUI compressor by default see http://documentcloud.github.com/jammit/#compressors
template_function: _.template

javascripts:
  common:
    - public/javascripts/common/**/*.js
  shelby:
    # backbone && underscore
    - public/javascripts/backbone/underscore-min.js
    - public/javascripts/backbone/backbone-min.js
    - public/javascripts/backbone/backbone-relational.js
    #underscore mixins
    - public/javascripts/underscore.inflection.js
    # shelby backbone app
    - public/javascripts/app/routers/*.js
    - public/javascripts/app/models/*.js
    - public/javascripts/app/collections/*.js
    - public/javascripts/app/views/**/*.js
    - public/javascripts/app/utils/*.js

stylesheets:
  common:
    - public/stylesheets/screen.css
  #h5bp:
    #- public/stylesheets/h5bp/*.css
