package_assets: on
compress_assets: on
# NOTE: The most recent version of jammit (0.6.5) includes ruby-yui-compressor (https://github.com/sstephenson/ruby-yui-compressor) which
#  is at version 0.9.6 which includes yui-compressor version 2.4.4 which chokes on inline svg.  
#  So we're including a more recent (and fixed) version manually...
css_compressor_options:
  jar_file: lib/yui-compressor/yuicompressor-2.4.7.jar
javascript_compressor: yui
template_function: _.template

javascripts:
  shelby-jst:
    # JSTs
    - app/views/templates/**/*.jst
    
stylesheets:
  common:
    - public/stylesheets/screen.css
  seovideo:
    - public/stylesheets/seovideo.css
  radar:
    - public/stylesheets/radar.css
