package_assets: on
compress_assets: on
template_function: _.template

javascripts:
  common:
    - public/javascripts/common/**/*.js
  shelby:
    # JSTs
    - app/views/templates/**/*.jst
    # backbone && underscore
    - public/javascripts/backbone/underscore.js
    - public/javascripts/backbone/backbone.js
    - public/javascripts/backbone/backbone-relational.js
    - public/javascripts/backbone/backbone-support/support.js
    - public/javascripts/backbone/backbone-support/swapping_router.js
    - public/javascripts/backbone/backbone-support/composite_view.js
    # underscore mixins
    - public/javascripts/backbone/underscore.inflection.js
    # jQuery plugins
    - public/javascripts/jquery-plugins/jquery.scrollTo.js
    # swf
    - public/javascripts/swfobject.js
    # shelby backbone app - assets that need to be loaded in dependency order
    - public/javascripts/app/app.js
    - public/javascripts/app/models/share_model.view.js
    - public/javascripts/app/views/list_item.view.js
    - public/javascripts/app/views/frame.view.js
    - public/javascripts/app/views/list.view.js
    - public/javascripts/app/views/auto_scroll_frame_list.view.js
    - public/javascripts/app/views/reroll_entry.view.js
    - public/javascripts/app/views/dashboard.view.js
    - public/javascripts/app/views/roll_list.view.js
    - public/javascripts/app/views/roll.view.js
    - public/javascripts/app/views/roll_header.view.js
    - public/javascripts/app/views/roll_filter_controls.view.js
    - public/javascripts/app/views/filter_controls.view.js
    - public/javascripts/app/views/roll_selection_item.view.js
    - public/javascripts/app/views/rolling_selection_list.view.js
    - public/javascripts/app/views/frame_rolling_footer.view.js
    - public/javascripts/app/views/share.view.js
    - public/javascripts/app/views/frame_share.view.js
    - public/javascripts/app/browser.js
    - public/javascripts/app/utils/display_state.utils.js
    # shelby backbone app - all other assets
    - public/javascripts/app/playback/*.js
    - public/javascripts/app/models/lib/*.js
    - public/javascripts/app/models/**/*.js
    - public/javascripts/app/collections/*.js
    - public/javascripts/app/views/**/*.js
    - public/javascripts/app/routers/*.js
    - public/javascripts/app/utils/*.js
    
stylesheets:
  common:
    - public/stylesheets/screen.css
