development:
  adapter: redis
  connection: redis://localhost:6379/0
  # collecting off by default so that development environments aren't required to have redis installed
  collecting: false

staging:
  collecting: false

production-seo-1:
  adapter: redis
  connection: redis://108.166.56.26:6379/0
  collecting: true

production:
  adapter: redis
  connection: redis://108.166.56.26:6379/0
  collecting: true
