defaults: &defaults
  url: "http://shelby.tv"
  protocol_matching_url: "//shelby.tv"
  domain: "shelby.tv"
  secure_url: "https://shelby.tv"
  mobile_url: "http://m.shelby.tv"
  ios_app_url: "http://itunes.apple.com/us/app/shelby-genius/id556665733"
  avatar_url_root: "//s3.amazonaws.com/shelby-gt-user-avatars"
  roll_images_url_root: "//s3.amazonaws.com/shelby-gt-roll-images"
  missing_thumb_url: "http://shelby.tv/images/assets/missing_thumb.png"
  meta_description: "Watch the perfect stream of videos built for you and powered by your friends. Videos from Twitter, Facebook, Tumblr, YouTube, Vimeo, Hulu and the rest of the web."
  title: "Shelby.tv | The perfect stream of videos built for you and powered by your friends."
  root_paths: ['featured','community', 'channels', 'help', 'legal', 'search', 'following', 'preferences', 'likes', 'saves', 'stream']

development:
  <<: *defaults
  url: "http://localhost.shelby.tv:3000"
  protocol_matching_url: "//localhost.shelby.tv:3000"
  mobile_url: "http://localhost.shelby.tv:3000/m"
  #enable this if you're using a local API
  #avatar_url_root: "http://s3.amazonaws.com/dev-shelby-gt-user-avatars"
  #mobile_url: "http://192.168.1.6:3000/m"

test:
  <<: *defaults

staging:
  <<: *defaults
  protocol_matching_url: "//staging.shelby.tv"
  mobile_url: "http://m.shelby.tv"

production:
  <<: *defaults
