defaults: &defaults
  url: "http://shelby.tv"
  protocol_matching_url: "//shelby.tv"
  domain: "shelby.tv"
  secure_url: "https://shelby.tv"
  secure_form_root: "https://shelby.tv"
  mobile_url: "http://m.shelby.tv"
  ios_app_url: "http://shl.by/app"
  ios_app_id: "732244981"
  ios_url_scheme: "shelbytv://"
  amazon_app_url: "http://www.amazon.com/gp/product/B00HCOMTV0/ref=mas_pm_shelbytv"
  avatar_url_root: "//s3.amazonaws.com/shelby-gt-user-avatars"
  roll_images_url_root: "//s3.amazonaws.com/shelby-gt-roll-images"
  missing_thumb_url: "http://shelby.tv/images/assets/missing_thumb.png"
  meta_description: "Watch the perfect stream of videos built for you and powered by your friends. Videos from Twitter, Facebook, Tumblr, YouTube, Vimeo, Hulu and the rest of the web."
  title: "Shelby.tv | The perfect stream of videos built for you and powered by your friends."
  root_paths: ["channels", "community", "explore", "featured", "following", "help", "legal", "likes", "preferences", "saves", "search", "stream"]

  weinre: "http://192.168.2.19:8080/target/target-script-min.js#anonymous"

development:
  <<: *defaults
  url: "http://localhost.shelby.tv:3000"
  protocol_matching_url: "//localhost.shelby.tv:3000"
  mobile_url: "http://localhost.shelby.tv:3000/m"
  secure_form_root: "http://localhost.shelby.tv:3000"
  #enable this if you're using a local API
  #avatar_url_root: "http://s3.amazonaws.com/dev-shelby-gt-user-avatars"
  #mobile_url: "http://192.168.1.6:3000/m"

test:
  <<: *defaults
  secure_form_root: "https://staging.shelby.tv"

staging:
  <<: *defaults
  # if you're testing features that use these paths from alpha.shelby.tv, t
  # you may need to alter these values to from *staging.* to *alpha.*
  # TEMPORARY:
  url: "http://alpha.shelby.tv"
  # url: "http://staging.shelby.tv"
  protocol_matching_url: "//staging.shelby.tv"
  mobile_url: "http://m.shelby.tv"
  secure_form_root: "http://staging.shelby.tv"

production:
  <<: *defaults
