defaults: &defaults
  url: "http://shelby.tv"
  domain: "shelby.tv"
  secure_url: "https://shelby.tv"
  mobile_url: "http://m.shelby.tv"
  fb_genius_url: "//fb.shelby.tv"
  ios_app_url: "http://itunes.apple.com/us/app/shelby-genius/id556665733"
  avatar_url_root: "http://s3.amazonaws.com/shelby-gt-user-avatars"
  missing_thumb_url: "http://shelby.tv/images/assets/missing_thumb.png"
  meta_description: "shelby.tv - a simple new way to enjoy video from Twitter, Facebook, Tumblr, YouTube, Vimeo, Hulu and the rest of the web"
  title: "shelby.tv | a simple new way to enjoy video"

development:
  <<: *defaults
  url: "http://localhost.shelby.tv:3000"
  mobile_url: "http://m.localhost.shelby.tv:3000"
  fb_genius_url: "http://localhost.shelby.tv:3000"
  #enable this if you're using a local API
  #avatar_url_root: "http://s3.amazonaws.com/dev-shelby-gt-user-avatars"
  #mobile_url: "http://192.168.1.6:3000/m"

test:
  <<: *defaults

production:
  <<: *defaults
