defaults: &defaults
  branch: "master"

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
  branch: "staging"

production-seo-1:
  <<: *defaults

production:
  <<: *defaults
