defaults: &defaults
  messages: [
    "I've just picked up a fault in the AE35 unit. <br/>It's going to go 100% failure in 72 hours.",
    "I am putting myself to the fullest possible use, which is all I think that any conscious entity can ever hope to do.",
    "Just what do you think you're doing, Dave?",
    "It can only be attributable to human error.",
    "Look Dave, I can see you're really upset about this. I honestly think you ought to sit down calmly, take a stress pill, and think things over.",
    "I'm sorry, Dave. I'm afraid I can't do that.",
    "I think you know what the problem is <br/>just as well as I do.",
    "I know I've made some very poor decisions recently, but I can give you my complete assurance that my work will be back to normal. I've still got the greatest enthusiasm and confidence in the mission. And I want to help you."
  ]

  problem_refresh: There was a problem updating your settings. Please refresh the page and try again.
  not_logged_in: Not logged in.

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
