defaults: &defaults
  facebook_app_id: "115071338568035"
  genius_app_id: "305135322927840"
  genius_app_secret: "b616125302256c0dc06654cdd4bdf9bc"
  
development:
  <<: *defaults
  
test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
