defaults: &defaults
  facebook_app_id: "115071338568035"

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production-seo-1:
  <<: *defaults

production:
  <<: *defaults
