defaults: &defaults
  videos_youll_love: "Watch videos you'll love."
  discover_and_enjoy: "Discover and enjoy the <br/>best of web video."
  just_for_you: "A personal channel of video, picked just for you."
  powered_by_friends: "The best web video, powered by friends."
  no_search_required: "Great video, no searching required."

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production-seo-1:
  <<: *defaults

production:
  <<: *defaults
