defaults: &defaults
  videos_youll_love: "Watch videos you'll love."
  discover_and_enjoy: "Discover and enjoy the <br/>best of web video."
  just_for_you: "A personal channel of video, picked just for you."
  powered_by_friends: "The best web video, powered by friends."
  no_search_required: "Great video, no searching required."
  discover_love: "Discover videos you and your friends will love."

  cta: "Discover videos you and your friends will love."
  cta_body: "Get the best of web video, personalized to your interests <br/>and available wherever you are."
  cta_button: "Get the Free App"

  stream: "See what video your friends like,<br/>from all over the web."
  stream_body: "Shelby.tv collects videos from across the web and organizes them into <br/>a single stream, showing you the information that matters to you."

  social: "Like videos and Shelby uncovers more to watch."
  social_body: "Shelby.tv delivers smart recommendations based on your behavior and gets better over time."

  ipadbeta:
    optin:
      head: Welcome to the Shelby.tv iPad Beta
      message: "You're one of a few to have early access."
      directions: [
        "Visit <a href=\"http://shl.by/ipadbeta\" class=\"shelf__cta js-track-event\" data-ga_category=\"iPad Beta\" data-ga_action=\"Click to Download iPad Beta\">shl.by/ipadbeta</a> from your iPad.",
        "Follow the directions to install the app.",
        "Let us know what you think!"
      ]
    optout:
      head: Thank you for your time!
      message: [
        "We understand that you're not able to participate but we hope to see you back again soon!",
        "<small>*You're free to try out our iPad beta by visiting <a href=\"http://shl.by/ipadbeta\" class=\"shelf__cta js-track-event\" data-ga_category=\"iPad Beta\" data-ga_action=\"Click to Download iPad Beta\">shl.by/ipadbeta</a> from your device!</small>"
      ]
    support: "Questions? Concerns? Comments? Feel free to <a href=\"mailto:feedback@shelby.tv\" class=\"js-track-event\" data-ga_category=\"iPad Beta\" data-ga_action=\"Click to Contact Us\">contact us</a>!"

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
