defaults: &defaults
  videos_youll_love: "Watch videos you'll love."
  discover_and_enjoy: "Discover and enjoy the best of web video."
  just_for_you: "The best web video, picked just for you."
  powered_by_friends: "Your personal channel of video, powered by friends."

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
