defaults: &defaults
  mobile_subdirectory: ""
  default_limit: 10
  supported_providers: ["youtube","vimeo","dailymotion"]
  button_gray_flexible: 'button_primer button_command button_command--flexible button_gray'
  load_more_button_class: 'button_primer button_command button_command--flexible button_gray two-thirds js-load-more'
  roll_types: {
    featured: 'featured',
    likes: 'likes',
    me: 'me',
    shares: 'shares',
    stream: 'stream',
    user: 'user'
  }

  # roll_model_types:
  #   # // special rolls that have not yet been updated to their specific type default to :special_roll
  #   special_roll : 10  # // <-- faux
  #   special_public : 11 # // <-- faux
  #   special_hearted : 12
  #   special_watch_later : 13
  #   # //Differentiate special_public rolls of real shelby users and those faux-users whome we deem special
  #   special_public_real_user : 15 # // <-- real
  #   special_public_upgraded : 16  # // <-- real
  #   # // special rolls are < all_special_rolls (convenience)
  #   all_special_rolls: 17
  #   # // User-created non-collaborative public rolls (previously these were collaborative, we're changing that)
  #   user_public : 30
  #   # // Company-created collaborative public rolls
  #   global_public : 31
  #   # // User-created collaborative private rolls
  #   user_private : 50
  #   # // User-created private conversations (aka Discussion Rolls)
  #   user_discussion_roll : 51
  #   genius : 70

  roll_followings: following

  preferences_sections: {
    notifications: 'notifications',
    profile: 'profile',
    sources: 'sources'
  }

  email_notifications:
    email_updates: News and Updates<br/> <em>Keep me updated with new stuff from Shelby.</em>
    like_notifications: Likes<br/> <em>Notify me when someone Likes my videos.</em>
    reroll_notifications: Shares<br/> <em>Notify me when someone Re-Shares my video.</em>
    comment_notifications: Comments<br/> <em>Notify me when someone comments on a video I share.</em>
    roll_activity_notifications: Profile Activity<br/> <em>Notify me when someone new Follows me.</em>

  ga_category: Mobile



development:
  <<: *defaults
  mobile_subdirectory: "/m"

test:
  <<: *defaults

staging:
  <<: *defaults
  mobile_subdirectory: "/m"

production:
  <<: *defaults
