defaults: &defaults
  onboarding_path: "/onboarding/"
  default_limit: 10
  supported_providers: ["youtube","vimeo", "dailymotion"]
  button_gray_flexible: 'button_primer button_command button_command--flexible button_gray'

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
