defaults: &defaults
  mobile_subdirectory: ""
  amazon_subdirectory: "/amazonapp"
  default_limit: 10
  supported_providers: ["youtube","vimeo","dailymotion"]
  button_gray_flexible: 'button_primer button_command button_command--flexible button_gray'
  load_more_button_class: 'button_primer button_command button_command--flexible button_gray two-thirds js-load-more'
  roll_types: {
    activity: 'activity',
    featured: 'featured',
    likes: 'likes',
    me: 'me',
    stream: 'stream',
    user: 'user'
  }

  roll_followings: following

  preferences_sections: {
    notifications: 'notifications',
    profile: 'profile',
    sources: 'sources'
  }

  email_notifications:
    email_updates: News and Updates<br/> <em>Keep me updated with new stuff from Shelby.</em>
    like_notifications: Likes<br/> <em>Notify me when someone Likes my videos.</em>
    reroll_notifications: Shares<br/> <em>Notify me when someone Re-Shares my video.</em>
    comment_notifications: Comments<br/> <em>Notify me when someone comments on a video I share.</em>
    roll_activity_notifications: Profile Activity<br/> <em>Notify me when someone new Follows me.</em>

  ga_category: Mobile

  inline_cta:
    sources:
      path: /preferences/sources
      hook: sources
      image_url: add-video-bkgd.png
      label: Add Video
      message: <em>Check out</em> a few areas of content to personalize your video stream.
    social:
      path: //api.shelby.tv/auth/fb?redir_query=connecting%3Dfacebook
      hook: social
      label: Facebook
      message: <em>Connect to social</em> to see videos your friends are sharing and so others know who you are.

development:
  <<: *defaults
  mobile_subdirectory: "/m"

  inline_cta:
    sources:
      path: /m/preferences/sources
      hook: sources
      image_url: add-video-bkgd.png
      label: Add Video
      message: <em>Check out</em> a few areas of content to personalize your video stream.
    social:
      path: //api.shelby.tv/auth/fb?redir_query=connecting%3Dfacebook
      hook: social
      label: Facebook
      message: <em>Connect to social</em> to see videos your friends are sharing and so others know who you are.

test:
  <<: *defaults

staging:
  <<: *defaults
  mobile_subdirectory: "/m"

  inline_cta:
    sources:
      path: /m/preferences/sources
      hook: sources
      image_url: add-video-bkgd.png
      label: Add Video
      message: <em>Check out</em> a few areas of content to personalize your video stream.
    social:
      path: //api.shelby.tv/auth/fb?redir_query=connecting%3Dfacebook
      hook: social
      label: Facebook
      message: <em>Connect to social</em> to see videos your friends are sharing and so others know who you are.

production:
  <<: *defaults
