defaults: &defaults
  video_providers: ['youtube', 'vimeo', 'dailymotion', 'hulu']

development:
  <<: *defaults
  mobile_subdirectory: "/m"

test:
  <<: *defaults

staging:
  <<: *defaults
  mobile_subdirectory: "/m"

production:
  <<: *defaults
