defaults: &defaults
  bookmarklet_url_encoded: javascript:void(function(d)%7Bwindow.isShelbyBookmarklet%3Dtrue%3B_sbm%3Dd.createElement(%27SCRIPT%27)%3B_sbm.type%3D%27text/javascript%27%3B_sbm.src%3D%27//shelby.tv/assets/shelbify.js%27%3Bd.getElementsByTagName(%27head%27)%5B0%5D.appendChild(_sbm)%3B%7D)(document)%3B%0A
  video_providers: ['youtube', 'vimeo', 'dailymotion', 'hulu']
  radar_path: '/bookmarklet'
  radar_button_text: Video Radar

development:
  <<: *defaults
  bookmarklet_url_encoded: javascript:void(function(d)%7Bwindow.isShelbyBookmarklet%3Dtrue%3B_sbm%3Dd.createElement(%27SCRIPT%27)%3B_sbm.type%3D%27text/javascript%27%3B_sbm.src%3D%27//localhost.shelby.tv:3000/assets/shelbify.js%27%3Bd.getElementsByTagName(%27head%27)%5B0%5D.appendChild(_sbm)%3B%7D)(document)%3B%0A
  radar_button_text: Video Radar (Dev)

test:
  <<: *defaults

staging:
  <<: *defaults
  bookmarklet_url_encoded: javascript:void(function(d)%7Bwindow.isShelbyBookmarklet%3Dtrue%3B_sbm%3Dd.createElement(%27SCRIPT%27)%3B_sbm.type%3D%27text/javascript%27%3B_sbm.src%3D%27//staging.shelby.tv/assets/shelbify.js%27%3Bd.getElementsByTagName(%27head%27)%5B0%5D.appendChild(_sbm)%3B%7D)(document)%3B%0A
  radar_button_text: Video Radar (Staging)
production:
  <<: *defaults
