defaults: &defaults
  video_providers: ['youtube', 'vimeo', 'dailymotion', 'hulu']
  radar_path: '/radar'

development:
  <<: *defaults
  mobile_subdirectory: "/m"

test:
  <<: *defaults

staging:
  <<: *defaults
  mobile_subdirectory: "/m"

production:
  <<: *defaults
