defaults: &defaults
  bookmarklet_url_encoded: javascript%3Avoid%28%28function%28d%29%7Bwindow.isShelbyBookmarklet%3Dtrue%3B_sbm%3Dd.createElement%28%27SCRIPT%27%29%3B_sbm.type%3D%27text/javascript%27%3B_sbm.src%3D%27//shelby.tv/assets/shelbify.js%27%3Bd.getElementsByTagName%28%27head%27%29%5B0%5D.appendChild%28_sbm%29%3B%7D%29%28document%29%29%3B%0A
  video_providers: ['youtube', 'vimeo', 'dailymotion', 'hulu']
  radar_path: '/radar'
  radar_button_text: Video Radar

development:
  <<: *defaults
  bookmarklet_url_encoded: javascript%3Avoid%28%28function%28d%29%7Bwindow.isShelbyBookmarklet%3Dtrue%3B_sbm%3Dd.createElement%28%27SCRIPT%27%29%3B_sbm.type%3D%27text/javascript%27%3B_sbm.src%3D%27//localhost.shelby.tv:3000/assets/shelbify.js%27%3Bd.getElementsByTagName%28%27head%27%29%5B0%5D.appendChild%28_sbm%29%3B%7D%29%28document%29%29%3B%0A
  mobile_subdirectory: "/m"
  radar_button_text: Video Radar (Dev)

test:
  <<: *defaults

staging:
  <<: *defaults
  bookmarklet_url_encoded: javascript%3Avoid%28%28function%28d%29%7Bwindow.isShelbyBookmarklet%3Dtrue%3B_sbm%3Dd.createElement%28%27SCRIPT%27%29%3B_sbm.type%3D%27text/javascript%27%3B_sbm.src%3D%27//staging.shelby.tv/assets/shelbify.js%27%3Bd.getElementsByTagName%28%27head%27%29%5B0%5D.appendChild%28_sbm%29%3B%7D%29%28document%29%29%3B%0A
  mobile_subdirectory: "/m"
  radar_button_text: Video Radar (Staging)
production:
  <<: *defaults
