defaults: &defaults
  cross_site_key: "GoatsFTW"
  
development:
  <<: *defaults
  url: "http://api.gt.shelby.tv"
  
test:
  <<: *defaults

production:
  <<: *defaults
  url: "http://api.gt.shelby.tv"
