defaults: &defaults
  url: "http://api.shelby.tv"
  secure_url: "https://api.shelby.tv"
  protocol_matching_url: "//api.shelby.tv"
  login_form_url: "https://api.shelby.tv/authentications/login"
  signup_form_url: "https://api.shelby.tv/user/sign_in"
  signup_route: "/signup"
  popup_cohort_entrance_url: "https://api.shelby.tv/cohort_entrance/dottv/popup"
  version: "/v1"
  featured_user_id: "521264b4b415cc44c9000001"

development: &development
  <<: *defaults
  login_form_url: "https://api.staging.shelby.tv/authentications/login"
  url: "http://api.staging.shelby.tv"
  secure_url: "https://api.staging.shelby.tv"
  protocol_matching_url: "//api.staging.shelby.tv"
  login_form_url: "https://api.staging.shelby.tv/authentications/login?redir=http://localhost.shelby.tv:3000"
  signup_form_url: "https://api.staging.shelby.tv/user/sign_in"
  popup_cohort_entrance_url: "https://api.staging.shelby.tv/cohort_entrance/dottv/popup"

test:
  <<: *defaults

staging:
  <<: *development
  login_form_url: "https://api.staging.shelby.tv/authentications/login"

production:
  <<: *defaults
