defaults: &defaults
  url: "http://api.shelby.tv"
  secure_url: "https://api.shelby.tv"
  login_form_url: "https://api.shelby.tv/authentications/login"
  signup_form_url: "https://api.shelby.tv/user/sign_in"
  popup_cohort_entrance_url: "https://api.shelby.tv/cohort_entrance/early_access_a"
  version: "/v1"

development:
  <<: *defaults
  login_form_url: "https://api.shelby.tv/authentications/login?redir=http://localhost.shelby.tv:3000"
  popup_cohort_entrance_url: "http://localhost:4000/cohort_entrance/test/popup"
  
test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
