defaults: &defaults
  # there are num_steps steps in the signup flow
  # counting starts from 1
  num_steps: 3
  service_authentication_step: 2
  user_update_step: 3
  roll_categories: [
    {
      title :  'surprised',
      rolls : [
        {
          nickname : 'VICE',
          personal_roll_id : '4f907a9b9a725b46010005c7',
          description : 'Exploring uncomfortable truths',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'Buzzfeed',
          personal_roll_id : '4f9577c488ba6b15ec0084c7',
          description : 'Social content on the web',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'Creators Project',
          personal_roll_id : '4fbbc4211c1cf42b91002eac',
          description : 'Tech in music, art, film, and design',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'Blank on Blank',
          personal_roll_id : '',
          description : 'Unheard interviews with American icons',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'The Daily What',
          personal_roll_id : '4fa28d849a725b79c9000228',
          description : 'Hot off the Internets',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'The Onion',
          personal_roll_id : '4fc532169a725b2999000354',
          description : "America's finest news satire",
          avatar : '/images/avatar.jpg'
        }
      ]
    },
    {
      title : 'inspired',
      rolls : [
        {
          nickname : 'TED',
          personal_roll_id : '4fa054ff88ba6b09c8000e93',
          description : 'Ideas worth spreading',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'iamOTHER',
          personal_roll_id : '',
          description : 'Thinkers, innovators and outcasts',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'Life+Times',
          personal_roll_id : '',
          description : "JAY Z's digital experience",
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'Reserve Channel',
          personal_roll_id : '5005b00e9a725b0e150178fa',
          description : 'Extraordinary people and places',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : "Jamie Oliver's Food Tube",
          personal_roll_id : '',
          description : 'Great recipes',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'New York Times',
          personal_roll_id : '50522466b415cc5b81002080',
          description : 'Where the conversation begins',
          avatar : '/images/avatar.jpg'
        }
      ]
    },
    {
      title : 'entertained',
      rolls : [
        {
          nickname : 'GQ',
          personal_roll_id : '',
          description : 'Look sharp + live smart',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'Vogue',
          personal_roll_id : '',
          description : 'Defining the culture of fashion',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'Pitchfork',
          personal_roll_id : '4fa3e6309a725b3689001792',
          description : 'Essential guide to indie music',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'Above Average',
          personal_roll_id : '50951b06b415cc567800aa16',
          description : 'High-quality laughs',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'Grantland',
          personal_roll_id : '',
          description : 'Sports and pop culture',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'IGN',
          personal_roll_id : '',
          description : 'Inside scoop on videogames',
          avatar : '/images/avatar.jpg'
        }
      ]
    },
    {
      title : 'daring',
      rolls : [
        {
          nickname : 'GoPro',
          personal_roll_id : '4f91700d88ba6b2aab000fba',
          description : "World's most versatile camera",
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'Red Bull',
          personal_roll_id : '4fb413bb9a725b650900195a',
          description : "Prepare for maximum 'stoke factor'",
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'NetworkA',
          personal_roll_id : '4f987e9188ba6b58500122da',
          description : 'Intersection of Surf, Skate, Snow, BMX, Ski & Moto',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'RIDE',
          personal_roll_id : '',
          description: '22 skateboarding shows',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'Drive',
          personal_roll_id : '4f99e5069a725b1c7501c038',
          description : 'The culture of cars',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'Teton Gravity Research',
          personal_roll_id : '512d1f15b415cc5d8c0001cf',
          description : 'Ski and snowboard',
          avatar : '/images/avatar.jpg'
        }
      ]
    },
    {
      title : 'curious',
      rolls : [
        {
          nickname : 'PBS Idea Channel',
          personal_roll_id : '4faabca99a725b5cd50026a2',
          description : 'Pop culture, technology and art',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'Wired',
          personal_roll_id : '',
          description : 'Intersection of technology with all else',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'The Verge',
          personal_roll_id : '4fa1591f88ba6b78da0008b7',
          description : 'Intersection of technology, science, art, & culture',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'Crash Course',
          personal_roll_id : '4f95f29f88ba6b72c2004aed',
          description : 'Six awesome courses in from awesome channel',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'Sci Show',
          personal_roll_id : '',
          description : 'Science news and history',
          avatar : '/images/avatar.jpg'
        },
        {
          nickname : 'THNKR',
          personal_roll_id : '',
          description : 'Extraordinary access to the people, stories, ideas',
          avatar : '/images/avatar.jpg'
        }
      ]
    }
  ]

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults