defaults: &defaults
  roll_categories: [
    {
      title :  'surprised',
      rolls : [
        {
          nickname : 'VICE',
          description : 'Exploring uncomfortable truths'
        },
        {
          nickname : 'Buzzfeed',
          description : 'Social content on the web'
        },
        {
          nickname : 'Creators Project',
          description : 'Tech in music, art, film, and design'
        },
        {
          nickname : 'Blank on Blank',
          description : 'Unheard interviews with American icons'
        },
        {
          nickname : 'The Daily What',
          description : 'Hot off the Internets'
        },
        {
          nickname : 'The Onion',
          description : "America's finest news satire"
        }
      ]
    },
    {
      title : 'inspired',
      rolls : [
        {
          nickame : 'TED',
          description : 'Ideas worth spreading'
        },
        {
          nickname : 'iamOTHER',
          description : 'Thinkers, innovators and outcasts'
        },
        {
          nickname : 'Life+Times',
          description : "JAY Z's digital experience"
        },
        {
          nickname : 'Reserve Channel',
          description : 'Extraordinary people and places'
        },
        {
          nickname : "Jamie Oliver's Food Tube",
          description : 'Great recipes'
        },
        {
          nickname : 'New York Times',
          description : 'Where the conversation begins'
        }
      ]
    },
    {
      title : 'entertained',
      rolls : [
        {
          nickname : 'GQ',
          description : 'Look sharp + live smart'
        },
        {
          nickname : 'Vogue',
          description : 'Defining the culture of fashion'
        },
        {
          nickname : 'Pitchfork',
          description : 'Essential guide to indie music'
        },
        {
          nickname : 'Above Average',
          description : 'High-quality laughs'
        },
        {
          nickname : 'Grantland',
          description : 'Sports and pop culture'
        },
        {
          nickname : 'IGN',
          description : 'Inside scoop on videogames'
        }
      ]
    },
    {
      title : 'daring',
      rolls : [
        {
          nickname : 'GoPro',
          description : "World's most versatile camera"
        },
        {
          nickname : 'Red Bull',
          description : "Prepare for maximum 'stoke factor'"
        },
        {
          nickname : 'NetworkA',
          description : 'Intersection of Surf, Skate, Snow, BMX, Ski & Moto'
        },
        {
          nickname : 'RIDE',
          description: '22 skateboarding shows'
        },
        {
          nickname : 'Drive',
          description : 'The culture of cars'
        },
        {
          nickname : 'Teton Gravity Research',
          description : 'Ski and snowboard'
        }
      ]
    },
    {
      title : 'curious',
      rolls : [
        {
          nickname : 'PBS Idea Channel',
          description : 'Pop culture, technology and art'
        },
        {
          nickname : 'Wired',
          description : 'Intersection of technology with all else'
        },
        {
          nickname : 'The Verge',
          description : 'Intersection of technology, science, art, & culture'
        },
        {
          nickname : 'Crash Course',
          description : 'Six awesome courses in from awesome channel'
        },
        {
          nickname : 'Sci Show',
          description : 'Science news and history'
        },
        {
          nickname : 'THNKR',
          description : 'Extraordinary access to the people, stories, ideas'
        }
      ]
    }
  ]

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
