defaults: &defaults
  # there are num_steps steps in the signup flow
  # counting starts from 1
  num_steps: 3
  roll_selection_step: 1
  service_authentication_step: 2
  user_update_step: 3
  roll_categories: [
    {
      title :  'surprised',
      description: 'Do you love to watch <strong>surprising</strong> video? <br />Follow our hand-picked selections below.',
      rolls : [
        {
          nickname : 'VICE',
          personal_roll_id : '4f907a9b9a725b46010005c7',
          description : 'Exploring uncomfortable truths',
          avatar : 'http://i3.ytimg.com/i/n8zNIfYAQNdrFRrr8oibKw/mq1.jpg'
        },
        {
          nickname : 'Buzzfeed',
          personal_roll_id : '4f9577c488ba6b15ec0084c7',
          description : 'Social content on the web',
          avatar : 'http://i1.ytimg.com/i/pko_-a4wgz2u_DgDgd9fqA/mq1.jpg'
        },
        {
          nickname : 'Creators Project',
          personal_roll_id : '4fbbc4211c1cf42b91002eac',
          description : 'Tech in music, art, film, and design',
          avatar : 'http://i4.ytimg.com/i/_NaA2HkWDT6dliWVcvnkuQ/mq1.jpg'
        },
        {
          nickname : 'Blank on Blank',
          personal_roll_id : '4fa41c4f88ba6b0d4e00130f',
          description : 'Unheard interviews with American icons',
          avatar : 'http://i2.ytimg.com/i/9pO2YNforRbdwKOh09djKA/mq1.jpg'
        },
        {
          nickname : 'The Daily What',
          personal_roll_id : '4fa28d849a725b79c9000228',
          description : 'Hot off the Internets',
          avatar : 'http://24.media.tumblr.com/avatar_72e68a2dede0_512.png'
        },
        {
          nickname : 'The Onion',
          personal_roll_id : '4fc532169a725b2999000354',
          description : "America's finest news satire",
          avatar : 'http://i3.ytimg.com/i/fAOh2t5DpxVrgS9NQKjC7A/mq1.jpg'
        }
      ]
    },
    {
      title : 'inspired',
      description: 'Do you love to watch <strong>inspiring</strong> video? <br />Follow our hand-picked selections below.',
      rolls : [
        {
          nickname : 'TED',
          personal_roll_id : '4fa054ff88ba6b09c8000e93',
          description : 'Ideas worth spreading',
          avatar : 'http://i2.ytimg.com/i/AuUUnT6oDeKwE6v1NGQxug/mq1.jpg'
        },
        {
          nickname : 'iamOTHER',
          personal_roll_id : '519baa7eb415cc0191000007',
          description : 'Thinkers, innovators and outcasts',
          avatar : 'http://i2.ytimg.com/i/E560wL2ftkMrQL40LYFUVg/mq1.jpg'
        },
        {
          nickname : 'Life+Times',
          personal_roll_id : '519bab29b415cc0191000077',
          description : "JAY Z's digital experience",
          avatar : 'http://i3.ytimg.com/i/N-sc1xJr-QQNj_uNIM9wTA/mq1.jpg'
        },
        {
          nickname : 'Reserve Channel',
          personal_roll_id : '5005b00e9a725b0e150178fa',
          description : 'Extraordinary people and places',
          avatar : 'http://i2.ytimg.com/i/-LE7UowYotavwgFWKfN-nQ/mq1.jpg'
        },
        {
          nickname : "Jamie Oliver's Food Tube",
          personal_roll_id : '4f9d9c1a88ba6b56aa00150f',
          description : 'Great recipes',
          avatar : 'http://i1.ytimg.com/i/pSgg_ECBj25s9moCDfSTsA/mq1.jpg'
        },
        {
          nickname : 'New York Times',
          personal_roll_id : '50522466b415cc5b81002080',
          description : 'Where the conversation begins',
          avatar : 'http://i2.ytimg.com/i/qnbDFdCpuN8CMEg0VuEBqA/mq1.jpg'
        }
      ]
    },
    {
      title : 'entertained',
      description: 'Do you love to watch <strong>entertaining</strong> video? <br />Follow our hand-picked selections below.',
      rolls : [
        {
          nickname : 'GQ',
          personal_roll_id : '519bac7cb415cc01910000af',
          description : 'Look sharp + live smart',
          avatar : 'https://si0.twimg.com/profile_images/3658741077/a711cfb45b08e33226ea3845223bff15.jpeg'
        },
        {
          nickname : 'Vogue',
          personal_roll_id : '4fa062869a725b0c2c0010fc',
          description : 'Defining the culture of fashion',
          avatar : 'http://i3.ytimg.com/i/RXiA3h1no_PFkb1JCP0yMA/mq1.jpg'
        },
        {
          nickname : 'Pitchfork',
          personal_roll_id : '4fa3e6309a725b3689001792',
          description : 'Essential guide to indie music',
          avatar : 'http://i4.ytimg.com/i/7kI8WjpCfFoMSNDuRh_4lA/mq1.jpg'
        },
        {
          nickname : 'Above Average',
          personal_roll_id : '50951b06b415cc567800aa16',
          description : 'High-quality laughs',
          avatar : 'http://i3.ytimg.com/i/NVBYBxWj9dMHqKEl_V8HBQ/mq1.jpg'
        },
        {
          nickname : 'Grantland',
          personal_roll_id : '519bada3b415cc01910000e5',
          description : 'Sports and pop culture',
          avatar : 'http://i4.ytimg.com/i/wLr_DYKR8aS0k4r8bB5I5Q/mq1.jpg'
        },
        {
          nickname : 'IGN',
          personal_roll_id : '4f987a5e9a725b032b002f13',
          description : 'Inside scoop on videogames',
          avatar : 'https://lh4.googleusercontent.com/-CUStYqbZjKk/AAAAAAAAAAI/AAAAAAAAAAA/-WVBoj_7FTs/s100-c-k/photo.jpg'
        }
      ]
    },
    {
      title : 'daring',
      description: 'Do you love to watch <strong>daring</strong> video? <br />Follow our hand-picked selections below.',
      rolls : [
        {
          nickname : 'GoPro',
          personal_roll_id : '4f91700d88ba6b2aab000fba',
          description : "World's most versatile camera",
          avatar : 'http://i2.ytimg.com/i/qhnX4jA0A5paNd1v-zEysw/mq1.jpg'
        },
        {
          nickname : 'Red Bull',
          personal_roll_id : '4fb413bb9a725b650900195a',
          description : "Prepare for maximum 'stoke factor'",
          avatar : 'http://i3.ytimg.com/i/blfuW_4rakIf2h6aqANefA/mq1.jpg'
        },
        {
          nickname : 'NetworkA',
          personal_roll_id : '4f987e9188ba6b58500122da',
          description : 'Intersection of Surf, Skate, Snow, BMX, Ski & Moto',
          avatar : 'https://lh6.googleusercontent.com/-hG8LNuSwl5c/AAAAAAAAAAI/AAAAAAAAAAA/ZD0mnHsVHX8/s100-c-k/photo.jpg'
        },
        {
          nickname : 'RIDE',
          personal_roll_id : '4f9ee11b9a725b6605001713',
          description: '22 skateboarding shows',
          avatar : 'https://lh5.googleusercontent.com/-oCkEPfbsgm8/AAAAAAAAAAI/AAAAAAAAAAA/lfSnlX_J83M/s100-c-k/photo.jpg'
        },
        {
          nickname : 'Drive',
          personal_roll_id : '4f99e5069a725b1c7501c038',
          description : 'The culture of cars',
          avatar : 'http://i2.ytimg.com/i/5rBpVgv83gYPZ593XwQUsA/mq1.jpg'
        },
        {
          nickname : 'Teton Gravity Research',
          personal_roll_id : '512d1f15b415cc5d8c0001cf',
          description : 'Ski and snowboard',
          avatar : 'http://i3.ytimg.com/i/ziB6WaaUPEFSE2X1TNqUTg/mq1.jpg'
        }
      ]
    },
    {
      title : 'curious',
      description: 'Do you love to watch <strong>curious</strong> video? <br />Follow our hand-picked selections below.',
      rolls : [
        {
          nickname : 'PBS Idea Channel',
          personal_roll_id : '4faabca99a725b5cd50026a2',
          description : 'Pop culture, technology and art',
          avatar : 'http://i4.ytimg.com/i/3LqW4ijMoENQ2Wv17ZrFJA/mq1.jpg'
        },
        {
          nickname : 'Wired',
          personal_roll_id : '4f9a08909a725b43ad00f798',
          description : 'Intersection of technology with all else',
          avatar : 'http://i3.ytimg.com/i/ftwRNsjfRo08xYE31tkiyw/mq1.jpg'
        },
        {
          nickname : 'The Verge',
          personal_roll_id : '4fa1591f88ba6b78da0008b7',
          description : 'Intersection of technology, science, art, & culture',
          avatar : 'http://i1.ytimg.com/i/ddiUEpeqJcYeBxX1IVBKvQ/mq1.jpg'
        },
        {
          nickname : 'Crash Course',
          personal_roll_id : '4f95f29f88ba6b72c2004aed',
          description : 'Six awesome courses in from awesome channel',
          avatar : 'http://i1.ytimg.com/i/X6b17PVsYBQ0ip5gyeme-Q/mq1.jpg'
        },
        {
          nickname : 'Sci Show',
          personal_roll_id : '4f9731be88ba6b5309025c59',
          description : 'Science news and history',
          avatar : 'http://i3.ytimg.com/i/ZYTClx2T1of7BRZ86-8fow/mq1.jpg'
        },
        {
          nickname : 'THNKR',
          personal_roll_id : '4fc8f77f88ba6b0881000995',
          description : 'Extraordinary access to the people, stories, ideas',
          avatar : 'https://lh4.googleusercontent.com/-s4bLGopD5b8/AAAAAAAAAAI/AAAAAAAAAAA/nU7h6CIJqT8/s60-c-k/photo.jpg'
        }
      ]
    }
  ]

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
