defaults: &defaults
  frame_actions: ['share_frame', 'roll_to_channel', 'search']

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production-seo-1:
  <<: *defaults

production:
  <<: *defaults
