defaults: &defaults
  shelby_twitter_user_id: "250202787"
  shelby_twitter_username: "shelby"

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production-seo-1:
  <<: *defaults

production:
  <<: *defaults
