defaults: &defaults
  #this setting is the threshold for when to show/hide the inline CTAs
  #after the specified amount of times a user has seen the stream, hide the CTAs
  anon_banner_session_count: 3
  anonymous_user_nickname: 'Anonymous'
  #fe fi fo faux fum, I smell a user_type of user_type 1
  user_type:
    real: 0
    faux: 1
    converted: 2
    service: 3
    anonymous: 4
    #ghost is not a real user_type. it's a hack to alleviate an edge case where helper.display_banners breaks.
    ghost: 99

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
