defaults: &defaults
  api_domain: 'api.shelby.tv'
  web_domain: 'shelby.tv'

development:
  <<: *defaults
  web_domain: 'localhost.shelby.tv:3000'

test:
  <<: *defaults
  web_domain: 'localhost.shelby.tv:3000'

production: &production
  <<: *defaults

arnold:
  <<: *production
